### PR TITLE
start on leaderboard

### PR DESCRIPTION
**Pull request by spookybear0**

### CODE REVIEW

**Review by ElectroFlameOfficial — APPROVED** [review]
i approve
yes

**Comment by ElectroFlameOfficial** [comment]
ay laica care to check this out?

**Review by Altenhh — APPROVED** [review]
I have little time to review this, but based on what I've seen from Discord, this looks to be good.

**Review by ElectroFlameOfficial — APPROVED** [review]
seems better

**Comment by ElectroFlameOfficial** [comment]
merging

**Pull request merged**
